---
- name: "Update apt packages"
  become: true
  apt:
    update_cache: yes

- name: "Upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "Remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: Install nodejs
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Install npm
  yum:
    name: npm
    state: present
    update_cache: yes

- name: install pm2
  become: true
  npm:
    name: pm2@3.2.2
    global: yes
    production: yes
    state: present

- name: "The remote environment"
  shell: env

- name: "Extract Artifact"
  unarchive:
    src: files/artifact/tar.gz
    dest: ~/backend-app/

- name: "Execute node start "
  shell: |
    cd backend-app
    npm install
    pm2 stop default
    pm2 start npm -- start